# Configuración directa de MongoDB Atlas
spring.data.mongodb.host=cluster0.zurfpj0.mongodb.net
spring.data.mongodb.username=yaelsanch1987_db_user
spring.data.mongodb.password=ABZdL6d1iQ2FxWkd
spring.data.mongodb.database=provider-nosql

# Forzar el uso del protocolo seguro SRV y habilitar el auto-ajuste
spring.data.mongodb.additional-properties.retryWrites=true
spring.data.mongodb.additional-properties.w=majority
