spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.auto-index-creation=true
# Configuración forzada para evitar errores de handshake SSL
spring.mongodb.driver.tls.allow-invalid-certificates=true
