# Nombre y Puerto (Diferente al de SQL para que no choquen)
spring.application.name=provider-nosql
server.port=8081

# Configuración de MongoDB
# Aquí conectamos a la base de datos llamada 'productos_nosql_db'
spring.data.mongodb.uri=mongodb://localhost:27017/productos_nosql_db

# Mostrar las operaciones en consola
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG